In [56]:
from configparser import ConfigParser
import psycopg2
import numpy as np
import pandas as pd
from sklearn import preprocessing
from sklearn.model_selection import train_test_split
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier
from sklearn.ensemble import GradientBoostingClassifier
from sklearn.svm import LinearSVC
from sklearn.metrics import recall_score, precision_score
#Can be very helpful to notice any imbalance in classes
from collections import Counter 

In [57]:
#Sourced from https://www.postgresqltutorial.com/postgresql-python/connect/
def config(filename='psql_sample.ini', section='postgresql'):
    parser = ConfigParser()
    # read config file
    parser.read(filename) 
 
    # get section, default to postgresql
    db = {}
    if parser.has_section(section):
        params = parser.items(section)
        for param in params:
            db[param[0]] = param[1]
    else:
        raise Exception('Section {0} not found in the {1} file'.format(section, filename))
 
    return db

In [58]:
#Get the configuration file as a python dictionary
cfg = config()

#Establish the connection and create a cursor to the database
try:
    print("Here's an attempt to connect to the database")
    conn = psycopg2.connect(**cfg)
    cursor = conn.cursor()
    print("Look's like it was a success")
    
except (Exception, psycopg2.DatabaseError) as error:
    print(error)

Here's an attempt to connect to the database
Look's like it was a success


In [59]:
#SELECT QUERY
try:
    #Lets get our data 
    cursor.execute("SELECT age_group,gender,measures.status,holiday,city,daily_high_temp,daily_low_temp,rain_amount,snow_amount,parks_percentage,retail_and_recreation_percentage,grocery_and_pharmacy_percentage,workplaces_percentage,residential_percentage,transit_stations_percentage,is_fatal,is_resolved,is_unresolved from data_mart.fact_table as fact inner join data_mart.mobility_dimension as mobility on fact.mobility_key=mobility.mobility_key inner join data_mart.weather_dimension as weather on fact.weather_key=weather.weather_key inner join data_mart.patient_dimension as patient on fact.patient_key=patient.patient_key inner join data_mart.special_measures_dimension as measures on fact.special_measures_key=measures.special_measures_key inner join data_mart.phu_location_dimension as phu on fact.phu_location_key=phu.phu_location_key inner join data_mart.reported_date_dimension as date on fact.reported_date_key=date.reported_date_key") 

    #Get the complete result set. It will be a list of tuples where each tuple is a row from the result set
    result_list = cursor.fetchall()
        
except (Exception, psycopg2.DatabaseError) as error:
    print(error)

In [60]:
#Ensure to run this cell at the end of all your experiments to close all connections
cursor.close()
conn.close()

In [61]:
#Now,  1
result_df = pd.DataFrame(result_list, columns=["age_group","gender","status","holiday","city","daily_high","daily_low","rain_amount","snow_amount", "parks_percentage", "retail_and_recreation_percentage","grocery_and_pharmacy_percentage","workplaces_percentage","residential_percentage","transit_stations_percentage",
                                               "is_fatal", "is_resolved","is_unresolved"])

result_df.drop(columns=['daily_high'], inplace=True)
result_df.drop(columns=['daily_low'], inplace=True)
result_df.drop(columns=['rain_amount'], inplace=True)
result_df.drop(columns=['snow_amount'], inplace=True)
result_df.drop(columns=['workplaces_percentage'], inplace=True)
result_df.drop(columns=['residential_percentage'], inplace=True)
result_df.drop(columns=['transit_stations_percentage'], inplace=True)
result_df.drop(columns=['is_resolved'], inplace=True)
result_df.drop(columns=['is_unresolved'], inplace=True)

result_df.head()

age_group gender                          status  holiday         city  \
0       40s   MALE  Private gathering restrictions    False  Mississauga   
1       50s   MALE  Private gathering restrictions    False  Mississauga   
2       <20   MALE  Private gathering restrictions    False  Mississauga   
3       30s   MALE  Private gathering restrictions    False  Mississauga   
4       20s   MALE  Private gathering restrictions    False    Newmarket   

   parks_percentage  retail_and_recreation_percentage  \
0              71.0                             -15.0   
1              71.0                             -15.0   
2              71.0                             -15.0   
3              71.0                             -15.0   
4               NaN                             -11.0   

   grocery_and_pharmacy_percentage  is_fatal  
0                             -1.0     False  
1                             -1.0     False  
2                             -1.0     False  
3                             -1.0     False  
4                              4.0     False

In [62]:
#Removing null values : 2
result_df["parks_percentage"].fillna(result_df["parks_percentage"].mean(), inplace=True)
result_df["grocery_and_pharmacy_percentage"].fillna(result_df["grocery_and_pharmacy_percentage"].mean(), inplace=True)
result_df["retail_and_recreation_percentage"].fillna(result_df["retail_and_recreation_percentage"].mean(), inplace=True)

result_df.head()

age_group gender                          status  holiday         city  \
0       40s   MALE  Private gathering restrictions    False  Mississauga   
1       50s   MALE  Private gathering restrictions    False  Mississauga   
2       <20   MALE  Private gathering restrictions    False  Mississauga   
3       30s   MALE  Private gathering restrictions    False  Mississauga   
4       20s   MALE  Private gathering restrictions    False    Newmarket   

   parks_percentage  retail_and_recreation_percentage  \
0         71.000000                             -15.0   
1         71.000000                             -15.0   
2         71.000000                             -15.0   
3         71.000000                             -15.0   
4         16.937927                             -11.0   

   grocery_and_pharmacy_percentage  is_fatal  
0                             -1.0     False  
1                             -1.0     False  
2                             -1.0     False  
3                             -1.0     False  
4                              4.0     False

In [63]:
#get counter 6
Counter(result_df['is_fatal'])

Counter({False: 83387, True: 1425})

In [64]:
#Get the labels 3
y_under = result_df["is_fatal"]#label


In [65]:
#normalize
#Normalizing data:
transform_data = result_df[["retail_and_recreation_percentage","grocery_and_pharmacy_percentage","parks_percentage"]]
X_normalized=preprocessing.normalize(transform_data,norm='l2')
normalize_part=pd.DataFrame(X_normalized,columns=transform_data.columns)
non_numerical=result_df[["status","age_group","is_fatal","city","gender","holiday"]]
result_data=pd.concat([non_numerical,normalize_part],axis=1)
result_data.head()

status age_group  is_fatal         city gender  \
0  Private gathering restrictions       40s     False  Mississauga   MALE   
1  Private gathering restrictions       50s     False  Mississauga   MALE   
2  Private gathering restrictions       <20     False  Mississauga   MALE   
3  Private gathering restrictions       30s     False  Mississauga   MALE   
4  Private gathering restrictions       20s     False    Newmarket   MALE   

   holiday  retail_and_recreation_percentage  grocery_and_pharmacy_percentage  \
0    False                         -0.206685                        -0.013779   
1    False                         -0.206685                        -0.013779   
2    False                         -0.206685                        -0.013779   
3    False                         -0.206685                        -0.013779   
4    False                         -0.534274                         0.194282   

   parks_percentage  
0          0.978310  
1          0.978310  
2          0.978310  
3          0.978310  
4          0.822682

In [66]:
#drop the label
result_data.drop(columns=['is_fatal'], inplace=True)

In [67]:
# Our features have categorical data. We need to convert them to one-hot encoders to get the best results.
new_result_df = pd.get_dummies(result_data)
new_result_df.head()

holiday  retail_and_recreation_percentage  grocery_and_pharmacy_percentage  \
0    False                         -0.206685                        -0.013779   
1    False                         -0.206685                        -0.013779   
2    False                         -0.206685                        -0.013779   
3    False                         -0.206685                        -0.013779   
4    False                         -0.534274                         0.194282   

   parks_percentage  status_Acitivies closures  status_Control  \
0          0.978310                          0               0   
1          0.978310                          0               0   
2          0.978310                          0               0   
3          0.978310                          0               0   
4          0.822682                          0               0   

   status_Lockdown  status_Other  status_Private gathering restrictions  \
0                0             0                                      1   
1                0             0                                      1   
2                0             0                                      1   
3                0             0                                      1   
4                0             0                                      1   

   status_Protect  ...  city_Mississauga  city_Newmarket  city_Oakville  \
0               0  ...                 1               0              0   
1               0  ...                 1               0              0   
2               0  ...                 1               0              0   
3               0  ...                 1               0              0   
4               0  ...                 0               1              0   

   city_Ottawa  city_Toronto  city_Whitby  gender_FEMALE  \
0            0             0            0              0   
1            0             0            0              0   
2            0             0            0              0   
3            0             0            0              0   
4            0             0            0              0   

   gender_GENDER DIVERSE  gender_MALE  gender_UNSPECIFIED  
0                      0            1                   0  
1                      0            1                   0  
2                      0            1                   0  
3                      0            1                   0  
4                      0            1                   0  

[5 rows x 32 columns]

In [68]:
#Undersampling of majority classes:  4
from imblearn.under_sampling import NearMiss
X = new_result_df.values#features
undersample = NearMiss(version=1,n_neighbors=3)
x_under, y_under = undersample.fit_resample(X,y_under)

In [69]:
X_train, X_test, y_train, y_test = train_test_split(x_under, y_under, test_size=0.33, shuffle=True, stratify=y_under)

In [70]:
#Let's see the no. of records per class in training and test set
print("Training set {} ".format(Counter(y_train)))
print("Test set {} ".format(Counter(y_test)))

Training set Counter({False: 955, True: 954}) 
Test set Counter({True: 471, False: 470}) 


In [71]:
#PART B
from sklearn.metrics import classification_report, confusion_matrix
from sklearn.metrics import classification_report, confusion_matrix
from sklearn.metrics import recall_score, precision_score, accuracy_score
import datetime
#Gradient Boosting


#X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.33, shuffle=True, stratify=y_under)
a = datetime.datetime.now()
classifier = GradientBoostingClassifier(n_estimators=20, learning_rate=0.75, max_features=2, max_depth=2, random_state=0)
classifier.fit(X_train, y_train)
predictions = classifier.predict(X_test)
b = datetime.datetime.now()
c = b - a

print('time in milliseconds')
print(c.total_seconds() * 1000)
print("Confusion Matrix:")
print(confusion_matrix(y_test, predictions))

print("Classification Report")
print(classification_report(y_test, predictions))

accuracy = accuracy_score(predictions, y_test) * 100
recall = recall_score(predictions, y_test) * 100
precision = precision_score(predictions, y_test) * 100

print("Accuracy of Gradient Boosting: {:.2f} %".format(accuracy))
print("Precision of Gradient Boosting: {:.2f} %".format(precision))
print("Recall of Gradient Boosting: {:.2f} %".format(recall))


time in milliseconds
91.598
Confusion Matrix:
[[403  67]
 [191 280]]
Classification Report
              precision    recall  f1-score   support

       False       0.68      0.86      0.76       470
        True       0.81      0.59      0.68       471

    accuracy                           0.73       941
   macro avg       0.74      0.73      0.72       941
weighted avg       0.74      0.73      0.72       941

Accuracy of Gradient Boosting: 72.58 %
Precision of Gradient Boosting: 59.45 %
Recall of Gradient Boosting: 80.69 %


In [72]:
#Random Forest
#X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, shuffle=True, stratify = y_under)

#create and fit random forest
a = datetime.datetime.now()#start time
rf = RandomForestClassifier(max_depth=2, random_state=0)
rf.fit(X_train, y_train)
y_pred = rf.predict(X_test)
b = datetime.datetime.now()#end time
c = b - a

print('time in milliseconds')
print(c.total_seconds() * 1000)

print("Confusion Matrix:")
print(confusion_matrix(y_test, y_pred))

print("Classification Report")
print(classification_report(y_test, y_pred))

accuracy = accuracy_score(y_pred, y_test) * 100
recall = recall_score(y_pred, y_test) * 100
precision = precision_score(y_pred, y_test) * 100

print("Accuracy of Random Forest: {:.2f} %".format(accuracy))
print("Precision of Random Forest: {:.2f} %".format(precision))
print("Recall of Random Forest: {:.2f} %".format(recall))


time in milliseconds
413.632
Confusion Matrix:
[[377  93]
 [185 286]]
Classification Report
              precision    recall  f1-score   support

       False       0.67      0.80      0.73       470
        True       0.75      0.61      0.67       471

    accuracy                           0.70       941
   macro avg       0.71      0.70      0.70       941
weighted avg       0.71      0.70      0.70       941

Accuracy of Random Forest: 70.46 %
Precision of Random Forest: 60.72 %
Recall of Random Forest: 75.46 %


In [73]:
#Decision Tree Algorithm:
#X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, shuffle=True, stratify=y)
from sklearn import tree
from matplotlib import pyplot as plt
import graphviz

a = datetime.datetime.now()
dt = DecisionTreeClassifier(criterion='entropy')
dt.fit(X_train, y_train)
y_pred = dt.predict(X_test)
b = datetime.datetime.now()
c = b - a

print('time in milliseconds')
print(c.total_seconds() * 1000)

print("Confusion Matrix:")
print(confusion_matrix(y_test, y_pred))

print("Classification Report")
print(classification_report(y_test, y_pred))

accuracy = accuracy_score(y_pred,y_test) * 100  
recall = recall_score(y_pred, y_test) * 100 
precision = precision_score(y_pred, y_test) * 100

print("Accuracy of Decision Tree: {:.2f} %".format(accuracy))
print("Recall of Decision Tree: {:.2f} %".format(recall))
print("Precision of Decision Tree: {:.2f} %".format(precision))



time in milliseconds
18.568
Confusion Matrix:
[[423  47]
 [170 301]]
Classification Report
              precision    recall  f1-score   support

       False       0.71      0.90      0.80       470
        True       0.86      0.64      0.74       471

    accuracy                           0.77       941
   macro avg       0.79      0.77      0.77       941
weighted avg       0.79      0.77      0.77       941

Accuracy of Decision Tree: 76.94 %
Recall of Decision Tree: 86.49 %
Precision of Decision Tree: 63.91 %


In [74]:
dot_data = tree.export_graphviz(dt, out_file=None) 
graph = graphviz.Source(dot_data) 
graph.render("DecisionTree") 

'DecisionTree.pdf'

In [75]:
#PART C
from sklearn.svm import OneClassSVM

clf = OneClassSVM(gamma='auto').fit(X_train)
y_pred = clf.predict(X_test)
#array([-1,  1,  1,  1, -1])
Score = clf.score_samples(X_test)
print(Score)
#array([1.7798..., 2.0547..., 2.0556..., 2.0561..., 1.7332...])


[783.51508707 759.7222725  790.45860349 794.17708018 789.07672603
 785.48352512 788.99219076 781.1568513  806.42303246 802.68815054
 799.8845826  787.43944558 777.50977755 787.53341843 751.67195228
 769.81610405 790.91944198 773.41998315 786.21922312 795.4040059
 786.21922312 773.7398396  796.04374601 772.12479468 797.94731186
 761.49149842 790.91944198 799.41014731 790.91907928 785.4006314
 786.86461623 796.75501822 805.11755811 794.78223657 799.66828618
 797.75602531 798.35345035 801.36104135 756.25631444 786.16546274
 754.33340317 801.09384596 795.950441   775.439937   799.15395188
 767.53837025 794.91334716 796.1570452  809.51298718 767.85806513
 788.45010186 804.79279551 754.59706776 791.05833805 796.5329363
 788.99219076 765.60570282 735.1335603  795.51051294 797.0407701
 790.30764948 809.80346943 745.29351177 781.48068556 780.96136412
 796.70784044 789.98675983 789.45343212 790.95709114 793.38920527
 793.24039601 803.82386195 758.24178822 792.36743474 779.79488588
 802.22065221 